# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
jobs:
- job: Job1
  steps:
  - script: echo Job1 - Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
      echo more information
    displayName: 'Run a multi-line script'
    condition: 
- job: Job2
  dependsOn: Job1
  steps:
  - script: echo Job2 Hello, world! New
    displayName: 'Run a one-line script'

- job: Job3
  dependsOn: Job2
  steps:
  - script: echo Job3 Hello, world! New
    displayName: 'Run a one-line script'
